// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMonitor;

#nullable disable

namespace WebMonitor.Migrations
{
    [DbContext(typeof(WebMonitorContext))]
    [Migration("20230801170032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("WebMonitor.Model.AllowedFeatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BatteryInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ComputerInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CpuUsage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DiskUsage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExtendedProcessInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FileBrowser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FileDownload")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FileUpload")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GpuUsage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MemoryUsage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NetworkUsage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NvidiaRefreshSettings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProcessAffinityChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProcessPriorityChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Processes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Terminal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AllowedFeatures");
                });

            modelBuilder.Entity("WebMonitor.Model.Db.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedFeaturesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllowedFeaturesId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebMonitor.Model.Db.User", b =>
                {
                    b.HasOne("WebMonitor.Model.AllowedFeatures", "AllowedFeatures")
                        .WithMany()
                        .HasForeignKey("AllowedFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllowedFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
